# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtd.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore,  QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(435, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 20, 83, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")

        self.Soprano = VoiceButton(self.frame, 0)
        self.Soprano.setChecked(True)
        self.Soprano.setObjectName("Soprano")
        self.gridLayout.addWidget(self.Soprano, 0, 0, 1, 1)

        self.alto = VoiceButton(self.frame, 1)
        self.alto.setObjectName("alto")
        self.gridLayout.addWidget(self.alto, 1, 0, 1, 1)
        self.tenor = VoiceButton(self.frame,2)
        self.tenor.setObjectName("tenor")
        self.gridLayout.addWidget(self.tenor, 2, 0, 1, 1)
        self.bass = VoiceButton(self.frame,3 )
        self.bass.setObjectName("bass")
        self.gridLayout.addWidget(self.bass, 3, 0, 1, 1)

        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(40, 190, 75, 23))
        self.addButton.setObjectName("addButton")

        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(140, 190, 75, 23))
        self.clearButton.setObjectName("clearButton")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(140, 30, 94, 111))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.Princ = RoleButton(self.frame_2, 0)
        self.Princ.setChecked(True)
        self.Princ.setObjectName("Princ")
        self.gridLayout_2.addWidget(self.Princ, 0, 0, 1, 1)

        self.minorlead = RoleButton(self.frame_2, 1)
        self.minorlead.setObjectName("minorlead")
        self.gridLayout_2.addWidget(self.minorlead, 1, 0, 1, 1)

        self.chorus = RoleButton(self.frame_2, 2)
        self.chorus.setObjectName("chorus")
        self.gridLayout_2.addWidget(self.chorus, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 160, 47, 14))
        self.label.setObjectName("label")

        self.charname = QtWidgets.QLineEdit(self.centralwidget)
        self.charname.setGeometry(QtCore.QRect(70, 160, 151, 20))
        self.charname.setObjectName("charname")
        self.nameList = QtWidgets.QListWidget(self.centralwidget)
        self.nameList.setGeometry(QtCore.QRect(270, 20, 141, 192))
        self.nameList.setObjectName("nameList")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.med = Mediator(self.charname, self.nameList)
        self.addButton.clicked.connect(self.med.addClick)
        self.clearButton.clicked.connect(self.med.clearClick)

        #con=Connect()
        #con. createConnection(self.charname,self.nameList, self.addButton, self.clearButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cast selection QtD"))
        self.Soprano.setText(_translate("MainWindow", "Soprano"))
        self.alto.setText(_translate("MainWindow", "Alto"))
        self.tenor.setText(_translate("MainWindow", "Tenor"))
        self.bass.setText(_translate("MainWindow", "Bass"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.Princ.setText(_translate("MainWindow", "Principal"))
        self.minorlead.setText(_translate("MainWindow", "Minor lead"))
        self.chorus.setText(_translate("MainWindow", "Chorus"))
        self.label.setText(_translate("MainWindow", "Name:"))
from buttons import RoleButton
from buttons import VoiceButton
from buttons import Mediator



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
